server:
  port: 8083

person:
  name: xw
  age: 22
  birth: 2022/03/23
  maps: {k1: v1, k2: v2}
  lists: [1,2,3,4]
  dog: {name: wangwang, age: 2}

#spring:
#  data:
#    mongodb:
#      host: 127.0.0.1
#      port: 27017
#      database: test1
#      username: jody
#      password: 0000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 0000
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      show-sql: true

